---
title: "Data Wrangling Final Project"
author: "Haoyuan Zhong"
date: "5/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# set up
```{r}
library(tidyverse)
library(stringr)
library(rvest)
library(reshape2)
```

# "I'd appreciate if I see a little more effort in data collection, e.g., combine this data from some other sources using scraping techniques."

# 1. Scraping data

```{r Scraping Data}
url1 <- "https://www.futbin.com/players?page=1&version=gold"
url2 <- "https://www.futbin.com/players?page=2&version=gold"
url3 <- "https://www.futbin.com/players?page=3&version=gold"
url4 <- "https://www.futbin.com/players?page=4&version=gold"
url5 <- "https://www.futbin.com/players?page=5&version=gold"
url6 <- "https://www.futbin.com/players?page=6&version=gold"
url7 <- "https://www.futbin.com/players?page=7&version=gold"
url8 <- "https://www.futbin.com/players?page=8&version=gold"
url9 <- "https://www.futbin.com/players?page=9&version=gold"
url10 <-"https://www.futbin.com/players?page=10&version=gold"
url11 <-"https://www.futbin.com/players?page=11&version=gold"
url12 <-"https://www.futbin.com/players?page=12&version=gold"
url13 <-"https://www.futbin.com/players?page=13&version=gold"
url14 <-"https://www.futbin.com/players?page=14&version=gold"
url15 <-"https://www.futbin.com/players?page=15&version=gold"
url16 <-"https://www.futbin.com/players?page=16&version=gold"
url17 <-"https://www.futbin.com/players?page=17&version=gold"
url18 <-"https://www.futbin.com/players?page=18&version=gold"
url19 <-"https://www.futbin.com/players?page=19&version=gold"
url20 <-"https://www.futbin.com/players?page=20&version=gold"
url21 <-"https://www.futbin.com/players?page=21&version=gold"
url22 <-"https://www.futbin.com/players?page=22&version=gold"
url23 <-"https://www.futbin.com/players?page=23&version=gold"
url24 <-"https://www.futbin.com/players?page=24&version=gold"
url25 <-"https://www.futbin.com/players?page=25&version=gold"
url26 <-"https://www.futbin.com/players?page=26&version=gold"
url27 <-"https://www.futbin.com/players?page=27&version=gold"
url28 <-"https://www.futbin.com/players?page=28&version=gold"
url29 <-"https://www.futbin.com/players?page=29&version=gold"
url30 <-"https://www.futbin.com/players?page=30&version=gold"
url31 <-"https://www.futbin.com/players?page=31&version=gold"
url32 <-"https://www.futbin.com/players?page=32&version=gold"
url33 <-"https://www.futbin.com/players?page=33&version=gold"
url34 <-"https://www.futbin.com/players?page=34&version=gold"
url35 <-"https://www.futbin.com/players?page=35&version=gold"
url36 <-"https://www.futbin.com/players?page=36&version=gold"
url37 <-"https://www.futbin.com/players?page=37&version=gold"
url38 <-"https://www.futbin.com/players?page=38&version=gold"
url39 <-"https://www.futbin.com/players?page=39&version=gold"
url40 <-"https://www.futbin.com/players?page=40&version=gold"

# player1 <- url1 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player1 <- as.tibble(player1[[1]])

# player2 <- url2 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)
  
# player2 <- as.tibble(player2[[1]])

# player3 <- url3 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player3 <- as.tibble(player3[[1]])

# player4 <- url4 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player4 <- as.tibble(player4[[1]])

# player5 <- url5 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player5 <- as.tibble(player5[[1]])

# player6 <- url6 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player6 <- as.tibble(player6[[1]])

# player7 <- url7 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player7 <- as.tibble(player7[[1]])

# player8 <- url8 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player8 <- as.tibble(player8[[1]])

# player9 <- url9 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player9 <- as.tibble(player9[[1]])

# player10 <- url10 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player10 <- as.tibble(player10[[1]])

# player_1 <- rbind(player1, player2, player3, player4, player5, player6, player7, player8, player9, player10)

# player11 <- url11 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player11 <- as.tibble(player11[[1]])

# player12 <- url12 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player12 <- as.tibble(player12[[1]])

# player13 <- url13 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player13 <- as.tibble(player13[[1]])

# player14 <- url14 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player14 <- as.tibble(player14[[1]])

# player15 <- url15 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player15 <- as.tibble(player15[[1]])

# player16 <- url16 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player16 <- as.tibble(player16[[1]])

# player17 <- url17 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player17 <- as.tibble(player17[[1]])

# player18 <- url18 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player18 <- as.tibble(player18[[1]])

# player19 <- url19 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player19 <- as.tibble(player19[[1]])

# player20 <- url20 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player20 <- as.tibble(player20[[1]])

# player_2 <- rbind(player11, player12, player13, player14, player15, player16, player17, player18, player19, player20)

# player21 <- url21 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player21 <- as.tibble(player21[[1]])

# player22 <- url22 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player22 <- as.tibble(player22[[1]])

# player23 <- url23 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player23 <- as.tibble(player23[[1]])

# player24 <- url24 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player24 <- as.tibble(player24[[1]])

# player25 <- url25 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player25 <- as.tibble(player25[[1]])

# player26 <- url26 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)


# player26 <- as.tibble(player26[[1]])

# player27 <- url27 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player27 <- as.tibble(player27[[1]])

# player28 <- url28 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player28 <- as.tibble(player28[[1]])

# player29 <- url29 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player29 <- as.tibble(player29[[1]])

# player30 <- url30 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player30 <- as.tibble(player30[[1]])

# player_3 <- rbind(player21, player22, player23, player24, player25, player26, player27, player28, player29, player30)

# player31 <- url31 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player31 <- as.tibble(player31[[1]])

# player32 <- url32 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player32 <- as.tibble(player32[[1]])

# player33 <- url33 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player33 <- as.tibble(player33[[1]])

# player34 <- url34 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player34 <- as.tibble(player34[[1]])

# player35 <- url35 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player35 <- as.tibble(player35[[1]])

# player36 <- url36 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player36 <- as.tibble(player36[[1]])

# player37 <- url37 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player37 <- as.tibble(player37[[1]])

# player38 <- url38 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player38 <- as.tibble(player38[[1]])

# player39 <- url39 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player39 <- as.tibble(player39[[1]])

# player40 <- url40 %>%
#   read_html() %>%
#   html_nodes("table") %>%
#   html_table(fill = TRUE)

# player40 <- as.tibble(player40[[1]])

# player_4 <- rbind(player31, player32, player33, player34, player35, player36, player37, player38, player39, player40)

# player_raw <- rbind(player_1, player_2, player_3, player_4)
                      
# player_raw

# write_csv(player_raw, 'FIFA21 player raw.csv')
backup_player_raw <- read_csv("/Users/jayhaoyuanzhong/Documents/Rutgers Data Science/Spring 2021/DATA WRANGLING/Project/Final/FIFA21 player raw.csv")
player_raw <- backup_player_raw
player_raw
```

# 2. Completed dataset from Kaggle
```{r}
FIFA <- read_csv("/Users/jayhaoyuanzhong/Documents/Rutgers Data Science/Spring 2021/DATA WRANGLING/Project/Final/players_21.csv") 
dim(FIFA)
summary(FIFA)
as.tibble(FIFA)
```


# 3. dataset cleaning
```{r}
# Scraping data
sum(is.na(player_raw))
player_final_1 <- player_raw %>%
  select(X1, X2, X3, X5, X6, X7, X9, X10, X11, X12, X13, X14) %>%
  mutate(X5 = str_replace_all(X5, '[K]', '')) %>%
  mutate(X5 = as.numeric(X5)) %>%
  filter(X5 < 500) %>%
  mutate(X5 = X5*1000) %>%
  filter(X3 != c("GK")) %>%
  rename("Name"= X1,"Rating" = X2, "Position" = X3,"Price" = X5,"skill_moves" = X6,"weak_foot" = X7,"pace" = X9,"shooting" = X10," passing" = X11,"dribbling" = X12,"defending" = X13,"physic" = X14)

player_final_1

player_final_2 <- player_raw %>%
  select(X1, X2, X3, X5, X6, X7, X9, X10, X11, X12, X13, X14) %>%
  mutate(X5 = str_replace_all(X5, '[K]', '')) %>%
  mutate(X5 = as.numeric(X5)) %>%
  filter(X5 > 500) %>%
  filter(X3 != c("GK")) %>%
  rename("Name"= X1,"Rating" = X2, "Position" = X3,"Price" = X5,"skill_moves" = X6,"weak_foot" = X7,"pace" = X9,"shooting" = X10," passing" = X11,"dribbling" = X12,"defending" = X13,"physic" = X14)

player_final_2

player_final <- rbind(player_final_1, player_final_2) %>%
  filter(Price > 0)

player_final
dim(player_final)
summary(player_final)

# Complete Dataset
FIFA_Final <- FIFA %>%
  select(short_name, overall, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic) %>%
  rename("Name" = short_name, "Rating" = overall)
FIFA_Final <- na.omit(FIFA_Final)
FIFA_Final
```


# 3. Join on two dataset
```{r}
player_final_last <- extract(player_final, Name, c("FirstName", "LastName"), "([^ ]+) (.*)")
player_final_last
FIFA_Final_last <- extract(FIFA_Final, Name, c("FirstName", "LastName"), "([^ ]+) (.*)")
FIFA_Final_last

FIFA_players <- inner_join(player_final_last, FIFA_Final_last, by = c("LastName", "Rating", "pace")) %>%
  select(LastName, Rating, Position, Price, value_eur, wage_eur, skill_moves.x, weak_foot.x, pace, shooting.x, passing, dribbling.x, defending.x, physic.x) %>%
  rename("skill_moves" = skill_moves.x, "weak_foot" = weak_foot.x, "shooting" = shooting.x, "dribbling" = dribbling.x, "defending" = defending.x, "physic" = physic.x)

FIFA_players

```

# 4. EDA
```{r}
ggplot(FIFA_players, aes(x=Price)) + geom_boxplot() + ggtitle("Distribution of Price") + scale_x_continuous(trans = 'log',
                     breaks = c(1000, 5000, 10000, 50000, 
                                100000, 200000),
                     labels = c('1,000', '5,000', '10,000', 
                                '50,000', '100,000', '200,000'))

ggplot(FIFA_players, aes(x=value_eur)) + geom_boxplot() + ggtitle("Distribution of value_eur") + scale_x_continuous(trans = 'log')

ggplot(FIFA_players, aes(x=wage_eur)) + geom_boxplot() + ggtitle("Distribution of wage_eur") + scale_x_continuous(trans = 'log')

ggplot(FIFA_players, aes(x=Position)) + stat_count(width = 0.5) + labs(title="Position Count", x="Position",y="Count") 

ggplot(FIFA_players, aes(x=Price,y=Rating)) + geom_point(col='red') + labs(title='Rating vs. Price') +
  scale_x_continuous(trans = 'log')

ggplot(FIFA_players, aes(x=value_eur,y=Rating)) + geom_point(col='blue') + labs(title='Rating vs. value_eur') +
  scale_x_continuous(trans = 'log')

ggplot(FIFA_players, aes(x=wage_eur,y=Rating)) + geom_point(col='purple') + labs(title='Rating vs. wage_eur') +
  scale_x_continuous(trans = 'log',
                     breaks = c(1000, 5000, 10000, 50000, 
                                100000, 200000),
                     labels = c('1,000', '5,000', '10,000', 
                                '50,000', '100,000', '200,000'))



#filter to different position
# Attacker
FIFA_ST <- FIFA_players %>%
  filter(Position == c("ST")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_ST

FIFA_CF <- FIFA_players %>%
  filter(Position == c("CF")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_CF

FIFA_attacker <- rbind(FIFA_ST, FIFA_CF)
FIFA_attacker

# finding
cormat = cor(FIFA_attacker, method = "s")
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "black")+ 
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") + 
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 8, hjust = 1))+ 
  coord_fixed() + ggtitle("Attacker Correlation")



# Winger
FIFA_LM <- FIFA_players %>%
  filter(Position == c("LM")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_LM

FIFA_LW <- FIFA_players %>%
  filter(Position == c("LW")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_LW

FIFA_RM <- FIFA_players %>%
  filter(Position == c("RM")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_RM

FIFA_RW <- FIFA_players %>%
  filter(Position == c("RW")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_RW

FIFA_winger <- rbind(FIFA_RM, FIFA_LW, FIFA_LM, FIFA_RW)
FIFA_winger

# finding
cormat = cor(FIFA_winger, method = "s")
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "black")+ 
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") + 
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 8, hjust = 1))+ 
  coord_fixed() + ggtitle("Winger Correlation")




# Full Back
FIFA_LB <- FIFA_players %>%
  filter(Position == c("LB")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_LB

FIFA_LWB <- FIFA_players %>%
  filter(Position == c("LWB")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_LWB

FIFA_RB <- FIFA_players %>%
  filter(Position == c("RB")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_RB

FIFA_RWB <- FIFA_players %>%
  filter(Position == c("RWB")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_RWB

FIFA_FullBack <- rbind(FIFA_RB, FIFA_LWB, FIFA_LB, FIFA_RWB)
FIFA_FullBack

# finding
cormat = cor(FIFA_FullBack, method = "s")
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "black")+ 
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") + 
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 8, hjust = 1))+ 
  coord_fixed() + ggtitle("Full Back Correlation")




# Center Back
FIFA_centerback <- FIFA_players %>%
  filter(Position == c("CB")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_centerback

# finding
cormat = cor(FIFA_centerback, method = "s")
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "black")+ 
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") + 
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 8, hjust = 1))+ 
  coord_fixed() + ggtitle("Center Back Correlation")




# midfielder
FIFA_CAM <- FIFA_players %>%
  filter(Position == c("CAM")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_CAM

FIFA_CM <- FIFA_players %>%
  filter(Position == c("CM")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_CM

FIFA_CDM <- FIFA_players %>%
  filter(Position == c("CDM")) %>%
  select(Rating, Price, value_eur, wage_eur, skill_moves, weak_foot, pace, shooting, passing, dribbling, defending, physic)
FIFA_CDM

FIFA_midfielder <- rbind(FIFA_CM, FIFA_CAM, FIFA_CDM)
FIFA_midfielder

# finding
cormat = cor(FIFA_midfielder, method = "s")
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "black")+ 
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") + 
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 8, hjust = 1))+ 
  coord_fixed() + ggtitle("Midfielder Correlation")
```

# 5 Linear Model
```{r}
lm <- lm(Rating ~ Price + value_eur + wage_eur + skill_moves + weak_foot + pace + shooting + passing + dribbling + defending + physic, data=FIFA_players)
summary(lm)
```


# Finshed
